version: '3.1'
services:
  frontend:
    restart: always
    build: ./frontend
    container_name: app_frontend_prod
    command: ng build --prod
    ports:
      - '4200:4200'
    volumes:
     - ./frontend:/usr/src/frontend
     - /frontend/node_modules

  backend:
    build: ./api
    container_name: api_backend_prod
    command: php bin/phing-latest.phar build:prod
    ports:
      - '3000:3000'
    links:
      - postgres
      - frontend
    volumes:
      - ./api:/usr/src/api

  postgres:
    build: ./db
    ports:
      - '5432:5432'
    container_name: api_database_prod