version: '3.1'
services:
  frontend:
    build: ./frontend
    image: frontend:dev
    container_name: app_frontend
    command: npm start
    networks:
      - frontend
    ports:
      - '4200:4200'
    volumes:
     - ./frontend:/usr/src/frontend
     - /usr/src/frontend/node_modules

  backend:
    build: ./api
    image: backend:dev
    container_name: api_backend
    command: php bin/phing-latest.phar -Dno-composer
    networks:
      - frontend
      - backend
    ports:
      - '3000:3000'
    links:
      - postgres
      - frontend
    volumes:
      - ./api:/usr/src/api

  postgres:
    build: ./db
    image: postgres:dev
    networks:
      - backend
    ports:
      - '5433:5432'
    container_name: api_database
    volumes:
     - ./db/scripts/initial_data.sql:/docker-entrypoint-initdb.d/initial_data.sql

networks:
  frontend:
  backend: