FROM postgres:9.6-alpine

# Maintainer
MAINTAINER Andrey Moretti <andreymor@gmail.com>

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=leaseweb

#COPY ./scripts/initial_data.sql /docker-entrypoint-initdb.d/

EXPOSE 5433