imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pt_BR

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    assets:
        packages:
            vendor:
                base_path: "/vendor"
    session:
          handler_id:  session.handler.null
    fragments: ~
    http_method_override: true
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_service_name%"
        service:   "%database_service_use%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  "%database_charset%"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        mappings:
            ApiModel:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/Api/Model/Entity'
                prefix: Api\Model\Entity
                alias: ApiModel

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_rest:
    param_fetcher_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener: true
    service:
      view_handler: core.handler.rest_view
    allowed_methods_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json : true
            xml: true
        templating_formats:
            html: true
        force_redirects:
            html: false
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true

nelmio_api_doc:
    documentation:
        info:
            title: ASAP
            description: Gestor de conteúdo
            version: 1.0.0
    routes:
        path_patterns: # an array of regexps
            - ^/api

#Configuração de annotations para utilização do FOSREST em conjunto com SENSIO
sensio_framework_extra:
    view:    { annotations: true }
    router:  { annotations: true }

#Configuração do KNP PAGINATOR (utilizado nas consultas).
#Os valores aqui informados seguem os padrões utilizados na GRID. Não alterar
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements

#Configuração de EXTENSIONS para ORM DOCTRINE
#Até o presente momento, são utilizados apenas o sluggable, softdeletable(deleção logica)
#Possivelmente, utilizar-se-a o timestampable
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            #tree: true
            timestampable: true
            #sluggable: true
            softdeleteable: true